# The --unsafe-no-fsync decreases the load on the pod's filesystem [1], which in
# turn decreases the end-to-end tests duration. It is OK for us to use this flag
# because we are using a one-node etcd cluster. The fsync feature is used for
# the raft consensus protocol and is thus only useful when using 3 or more etcd
# nodes.
#
#  [1]: https://github.com/etcd-io/etcd/pull/11946 [2]:
#  https://etcd.io/docs/v3.5/tuning/#disk [3]: https://etcd.io/docs/v3.5/faq/
#
# custom service subnet allows us to have a fixed/predictable clusterIP for
# various addon Services such as ingress-nginx, Gateway etc.
# TODO: parameterize the service subnet range instead of hardcoding it so that it is defined in one place only
# It could be interpolated with ytt like for addons i.e https://github.com/cert-manager/cert-manager/blob/134398e939bb2b1401697eaf589405ad469cd609/make/e2e-setup.mk#L379
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
kubeadmConfigPatches:
  - |
    apiVersion: kubeadm.k8s.io/v1beta3
    kind: ClusterConfiguration
    metadata:
      name: config
    etcd:
      local:
        extraArgs:
          unsafe-no-fsync: "true"
    networking:
      serviceSubnet: 10.0.0.0/16
nodes:
  - role: control-plane
