# Default values for cert-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: quay.io/jetstack/cert-manager-controller
  tag: v0.2.3
  pullPolicy: IfNotPresent

createCustomResource: true

rbac:
  create: true
  serviceAccountName: default

# Optional additional arguments
extraArgs: []
  # Use this flag to set a namespace that cert-manager will use to store
  # supporting resources required for each ClusterIssuer (default is kube-system)
  # - --cluster-resource-namespace=kube-system

resources:
  requests:
    cpu: 10m
    memory: 32Mi

# Optional additional arguments for cert-manager
extraArgs: []

nodeSelector: {}

ingressShim:
  enabled: true

  # Optional additional arguments for ingress-shim
  extraArgs: []

  resources:
    requests:
      cpu: 10m
      memory: 32Mi

  image:
    repository: quay.io/jetstack/cert-manager-ingress-shim

    # Defaults to image.tag.
    # You should only change this if you know what you are doing!
    # tag: v0.2.3

    pullPolicy: IfNotPresent
