## Example Certificate that uses nginx ingress to validate requests
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: cm-http-nginx-k8s-group
spec:
  secretName: cm-http-nginx-k8s-group
  issuer: letsencrypt-staging
  domains:
  - cm-http-nginx.k8s.group
  acme:
    config:
    - domains:
      - cm-http-nginx.k8s.group
      http-01:
        ingressClass: nginx
---
## Example Certificate that uses gce ingress to validate requests
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: cm-http-gce-k8s-group
spec:
  secretName: cm-http-gce-k8s-group
  issuer: letsencrypt-staging
  domains:
  - cm-http-gce.k8s.group
  acme:
    config:
    - domains:
      - cm-http-gce.k8s.group
      http-01:
        ingressName: my-existing-ingress
---
## Example Certificate that uses clouddns to validate requests
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: cm-dns-clouddns-k8s-group
spec:
  secretName: cm-dns-clouddns-k8s-group
  issuer: letsencrypt-staging
  domains:
  - cm-dns-clouddns.k8s.group
  acme:
    config:
    - domains:
      - cm-dns-clouddns.k8s.group
      dns-01:
        provider: clouddns
