apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cert-manager
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cert-manager
    spec:
      containers:
      - name: cert-manager
        image: quay.io/jetstack/cert-manager:canary.1
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: cert-manager
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8081
  selector:
    app: cert-manager
